version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:latest
    ports:
      - "8080:8080"
    volumes:
      - /Users/slagter/opt/Devops-final-project/jenkins:/var/jenkins_home:rw
    user: "1000:1000"
    restart: always

  tomcat:
    image: tomcat:latest
    ports:
      - "8081:8080"
    volumes:
      - /Users/slagter/opt/Devops-final-project/tomcat:/usr/local/tomcat/webapps
    restart: always

